{{- if and .Values.api.enabled .Values.api.env.ENCRYPTION_KEY }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "heimdall.fullname" . }}-api-secret
  labels:
    {{- include "heimdall.api.labels" . | nindent 4 }}
type: Opaque
data:
  encryption-key: {{ .Values.api.env.ENCRYPTION_KEY | b64enc | quote }}
{{- end }}
