{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-api-config
  labels:
    {{- include "heimdall.api.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.api.env.NODE_ENV | quote }}
  PORT: {{ .Values.api.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.api.env.LOG_LEVEL | quote }}
  LOG_FORMAT: {{ .Values.api.env.LOG_FORMAT | quote }}
  DATA_DIR: {{ .Values.api.env.DATA_DIR | quote }}
{{- end }}
