{{- if and .Values.frontend.enabled .Values.podDisruptionBudget.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "heimdall.fullname" . }}-frontend
  labels:
    {{- include "heimdall.frontend.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.frontend.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.frontend.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.frontend.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.frontend.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "heimdall.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
