{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-frontend-config
  labels:
    {{- include "heimdall.frontend.labels" . | nindent 4 }}
data:
  VITE_API_URL: {{ include "heimdall.frontend.apiUrl" . | quote }}
{{- end }}
